packages:
  - 'packages/*'
  - 'apps/*'
  - 'tests/*'
  - 'games/*'

catalog:
  '@a-type/ui': 1.3.4
  'react': 19.0.0
  'react-dom': 19.0.0
  '@types/react': 19.0.2
  '@types/react-dom': 19.0.2
  typescript: 5.7.2
  unocss: 0.65.2
  '@unocss/transformer-variant-group': 0.65.2
  vitest: 2.1.8
  '@a-type/react-space': 0.2.16
  '@a-type/auth-client': 1.0.13
  '@a-type/auth': 0.6.9
  '@a-type/utils': 1.1.4
