packages:
  - 'packages/*'
  - 'apps/*'
  - 'tests/*'
  - 'games/**/*'
  - 'app'
  - 'services'
  - 'services/*'
  - 'homepage'

catalog:
  '@a-type/ui': 2.0.6
  'react': 19.1.0
  'react-dom': 19.1.0
  '@types/react': ^19.1.2
  '@types/react-dom': ^19.1.2
  typescript: 5.8.3
  unocss: ^66.0.0
  '@unocss/cli': '^66.0.0'
  '@unocss/transformer-variant-group': ^66.0.0
  vitest: 3.0.4
  '@a-type/react-space': 0.2.16
  '@a-type/auth-fetch': ^2.0.1
  '@a-type/auth-ui': ^1.0.17
  '@a-type/auth': 1.3.12
  '@a-type/utils': 1.1.5
  hono: 4.7.7
  zod: ^3.24.3
  '@hono/zod-validator': ^0.4.3
  '@cloudflare/workers-types': ^4.20250124.3
  '@paralleldrive/cuid2': ^2.2.2
  '@verdant-web/react-router': 0.8.0
  valtio: ^2.1.3
  '@react-three/fiber': 9.1.2
  wrangler: 4.9.1
  copyfiles: 2.4.1
  web-push: 3.6.7
  '@types/web-push': 3.6.4
  three: 0.175.0
  '@types/three': 0.175.0
  '@react-three/drei': 10.0.6
  vite: 6.3.2
  '@vitejs/plugin-react-swc': 3.9.0
