packages:
  - 'packages/*'
  - 'apps/*'
  - 'tests/*'
  - 'games/**/*'
  - 'app'
  - 'services'
  - 'services/*'
  - 'homepage'
  - 'jobs/*'

catalog:
  '@a-type/ui': 2.7.6
  '@a-type/react-space': 0.2.17
  '@a-type/auth-fetch': 2.1.2
  '@a-type/auth-ui': 1.1.0
  '@a-type/auth': 1.3.16
  '@a-type/utils': 1.1.5
  'react': 19.1.1
  'react-dom': 19.1.1
  '@types/react': ^19.1.9
  '@types/react-dom': ^19.1.7
  typescript: 5.9.2
  unocss: ^66.4.0
  '@unocss/cli': '^66.4.0'
  '@unocss/transformer-variant-group': ^66.4.0
  '@unocss/webpack': ^66.4.0
  vitest: 3.2.4
  hono: 4.7.11
  zod: ^3.25.64
  '@hono/zod-validator': ^0.7.0
  '@cloudflare/workers-types': ^4.20250803.0
  '@paralleldrive/cuid2': ^2.2.2
  '@verdant-web/react-router': 0.8.0
  valtio: ^2.1.5
  '@react-three/fiber': 9.1.2
  wrangler: 4.9.1
  copyfiles: 2.4.1
  web-push: 3.6.7
  '@types/web-push': 3.6.4
  three: 0.175.0
  '@types/three': 0.175.0
  '@react-three/drei': 10.0.6
  vite: 7.0.5
  '@vitejs/plugin-react-swc': 3.9.0
  kysely: 0.27.6
  '@a-type/kysely': 1.1.1
  kysely-d1: 0.3.0
  kysely-plugin-serialize: 0.8.2
  motion: 12.18.1
  '@dnd-kit/core': 6.3.1
  '@dnd-kit/utilities': 3.2.2
  '@dnd-kit/react': 0.1.18
  '@dnd-kit/abstract': 0.1.18
  '@dnd-kit/dom': 0.1.18
  '@dnd-kit/helpers': 0.1.18
  react-flip-toolkit: 7.2.4
  '@use-gesture/react': 10.3.1
  delay-cli: 2.0.0
  cross-env: 7.0.3
  zustand: 5.0.6
  immer: 10.1.1
  env-cmd: 10.1.0
  '@module-federation/rsbuild-plugin': 0.17.0
  '@module-federation/enhanced': 0.17.0
  '@rsbuild/core': 1.4.8
  '@rsbuild/plugin-react': 1.3.4
  date-fns: ^4.1.0
