packages:
  - 'packages/*'
  - 'apps/*'
  - 'tests/*'
  - 'games/**/*'
  - 'app'
  - 'services'

catalog:
  '@a-type/ui': 1.4.1
  'react': 19.0.0
  'react-dom': 19.0.0
  '@types/react': ^19.0.8
  '@types/react-dom': ^19.0.3
  typescript: 5.7.3
  unocss: 0.65.2
  '@unocss/transformer-variant-group': 0.65.2
  vitest: 3.0.4
  '@a-type/react-space': 0.2.16
  '@a-type/auth-fetch': ^1.0.2
  '@a-type/auth-ui': ^1.0.15
  '@a-type/auth': 1.3.8
  '@a-type/utils': 1.1.4
  hono: 4.6.19
  zod: ^3.24.1
  '@hono/zod-validator': ^0.4.2
  '@cloudflare/workers-types': ^4.20250124.3
  '@paralleldrive/cuid2': ^2.2.2
  '@verdant-web/react-router': 0.7.1
  valtio: ^2.1.3
  '@react-three/fiber': 9.0.0-rc.5
