/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Boolean': unknown;
    'ChatMessage': { kind: 'OBJECT'; name: 'ChatMessage'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'message': { name: 'message'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'user': { name: 'user'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; 'userId': { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'Date': unknown;
    'DateTime': unknown;
    'Friendship': { kind: 'OBJECT'; name: 'Friendship'; fields: { 'friend': { name: 'friend'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'ENUM'; name: 'FriendshipStatus'; ofType: null; } }; }; };
    'FriendshipFilterInput': { kind: 'INPUT_OBJECT'; name: 'FriendshipFilterInput'; isOneOf: false; inputFields: [{ name: 'status'; type: { kind: 'ENUM'; name: 'FriendshipStatus'; ofType: null; }; defaultValue: null }]; };
    'FriendshipInviteResponseInput': { kind: 'INPUT_OBJECT'; name: 'FriendshipInviteResponseInput'; isOneOf: false; inputFields: [{ name: 'friendshipId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'response'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'FriendshipStatus'; ofType: null; }; }; defaultValue: null }]; };
    'FriendshipResponseResult': { kind: 'OBJECT'; name: 'FriendshipResponseResult'; fields: { 'Friendship': { name: 'Friendship'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Friendship'; ofType: null; }; } }; 'friendships': { name: 'friendships'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Friendships'; ofType: null; }; } }; }; };
    'FriendshipStatus': { name: 'FriendshipStatus'; enumValues: 'accepted' | 'declined' | 'pending'; };
    'Friendships': { kind: 'OBJECT'; name: 'Friendships'; fields: { 'connection': { name: 'connection'; type: { kind: 'OBJECT'; name: 'FriendshipsConnection'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'FriendshipsConnection': { kind: 'OBJECT'; name: 'FriendshipsConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'FriendshipsConnectionEdge'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'FriendshipsConnectionEdge': { kind: 'OBJECT'; name: 'FriendshipsConnectionEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Friendship'; ofType: null; }; } }; }; };
    'GameChat': { kind: 'OBJECT'; name: 'GameChat'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'messages': { name: 'messages'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'GameChatMessagesConnection'; ofType: null; }; } }; }; };
    'GameChatMessagesConnection': { kind: 'OBJECT'; name: 'GameChatMessagesConnection'; fields: { 'edges': { name: 'edges'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'GameChatMessagesConnectionEdge'; ofType: null; }; }; }; } }; 'pageInfo': { name: 'pageInfo'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PageInfo'; ofType: null; }; } }; }; };
    'GameChatMessagesConnectionEdge': { kind: 'OBJECT'; name: 'GameChatMessagesConnectionEdge'; fields: { 'cursor': { name: 'cursor'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'node': { name: 'node'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ChatMessage'; ofType: null; }; } }; }; };
    'GameInviteResponse': { name: 'GameInviteResponse'; enumValues: 'accepted' | 'declined' | 'expired' | 'pending' | 'uninvited'; };
    'GameSession': { kind: 'OBJECT'; name: 'GameSession'; fields: { 'chat': { name: 'chat'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'GameChat'; ofType: null; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'gameId': { name: 'gameId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'gameVersion': { name: 'gameVersion'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'members': { name: 'members'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'GameSessionMembership'; ofType: null; }; }; }; } }; 'postGame': { name: 'postGame'; type: { kind: 'OBJECT'; name: 'GameSessionPostGame'; ofType: null; } }; 'startedAt': { name: 'startedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; } }; 'state': { name: 'state'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'GameSessionState'; ofType: null; }; } }; 'timezone': { name: 'timezone'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; }; };
    'GameSessionMembership': { kind: 'OBJECT'; name: 'GameSessionMembership'; fields: { 'gameSession': { name: 'gameSession'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'GameSession'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'user': { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; }; };
    'GameSessionPostGame': { kind: 'OBJECT'; name: 'GameSessionPostGame'; fields: { 'globalState': { name: 'globalState'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; } }; 'winnerIds': { name: 'winnerIds'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; } }; }; };
    'GameSessionState': { kind: 'OBJECT'; name: 'GameSessionState'; fields: { 'currentTurn': { name: 'currentTurn'; type: { kind: 'OBJECT'; name: 'Turn'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'playerState': { name: 'playerState'; type: { kind: 'SCALAR'; name: 'JSON'; ofType: null; } }; 'rounds': { name: 'rounds'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Round'; ofType: null; }; }; }; } }; 'status': { name: 'status'; type: { kind: 'ENUM'; name: 'GameSessionStatusValue'; ofType: null; } }; 'winnerIds': { name: 'winnerIds'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; } }; }; };
    'GameSessionStatusValue': { name: 'GameSessionStatusValue'; enumValues: 'active' | 'completed' | 'pending'; };
    'GameTurnInput': { kind: 'INPUT_OBJECT'; name: 'GameTurnInput'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; }; defaultValue: null }]; };
    'ID': unknown;
    'Int': unknown;
    'JSON': unknown;
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'acceptTermsOfService': { name: 'acceptTermsOfService'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; 'prepareGameSession': { name: 'prepareGameSession'; type: { kind: 'OBJECT'; name: 'GameSession'; ofType: null; } }; 'respondToFriendshipInvite': { name: 'respondToFriendshipInvite'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'FriendshipResponseResult'; ofType: null; }; } }; 'respondToGameInvite': { name: 'respondToGameInvite'; type: { kind: 'OBJECT'; name: 'GameSessionMembership'; ofType: null; } }; 'sendFriendshipInvite': { name: 'sendFriendshipInvite'; type: { kind: 'OBJECT'; name: 'SendFriendshipInviteResult'; ofType: null; } }; 'sendGameInvite': { name: 'sendGameInvite'; type: { kind: 'OBJECT'; name: 'GameSessionMembership'; ofType: null; } }; 'sendMessage': { name: 'sendMessage'; type: { kind: 'OBJECT'; name: 'SendChatMessageResult'; ofType: null; } }; 'setSendEmailUpdates': { name: 'setSendEmailUpdates'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; 'startGameSession': { name: 'startGameSession'; type: { kind: 'OBJECT'; name: 'GameSession'; ofType: null; } }; 'submitTurn': { name: 'submitTurn'; type: { kind: 'OBJECT'; name: 'SubmitTurnResult'; ofType: null; } }; 'updateGameSession': { name: 'updateGameSession'; type: { kind: 'OBJECT'; name: 'UpdateGameSessionResult'; ofType: null; } }; 'updateUserInfo': { name: 'updateUserInfo'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; }; };
    'Node': { kind: 'INTERFACE'; name: 'Node'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; possibleTypes: 'ChatMessage' | 'Friendship' | 'Friendships' | 'GameChat' | 'GameSession' | 'GameSessionMembership' | 'GameSessionState' | 'User'; };
    'PageInfo': { kind: 'OBJECT'; name: 'PageInfo'; fields: { 'endCursor': { name: 'endCursor'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'hasNextPage': { name: 'hasNextPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'hasPreviousPage': { name: 'hasPreviousPage'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'startCursor': { name: 'startCursor'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; }; };
    'PrepareGameSessionInput': { kind: 'INPUT_OBJECT'; name: 'PrepareGameSessionInput'; isOneOf: false; inputFields: [{ name: 'gameId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }]; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'friendships': { name: 'friendships'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Friendships'; ofType: null; }; } }; 'gameSession': { name: 'gameSession'; type: { kind: 'OBJECT'; name: 'GameSession'; ofType: null; } }; 'me': { name: 'me'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; 'memberships': { name: 'memberships'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'GameSessionMembership'; ofType: null; }; }; } }; 'node': { name: 'node'; type: { kind: 'INTERFACE'; name: 'Node'; ofType: null; } }; 'nodes': { name: 'nodes'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'INTERFACE'; name: 'Node'; ofType: null; }; }; } }; }; };
    'RespondToGameInviteInput': { kind: 'INPUT_OBJECT'; name: 'RespondToGameInviteInput'; isOneOf: false; inputFields: [{ name: 'inviteId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'response'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'GameInviteResponse'; ofType: null; }; }; defaultValue: null }]; };
    'Round': { kind: 'OBJECT'; name: 'Round'; fields: { 'roundIndex': { name: 'roundIndex'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'turns': { name: 'turns'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Turn'; ofType: null; }; }; }; } }; }; };
    'SendChatMessageInput': { kind: 'INPUT_OBJECT'; name: 'SendChatMessageInput'; isOneOf: false; inputFields: [{ name: 'gameSessionId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'message'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'SendChatMessageResult': { kind: 'OBJECT'; name: 'SendChatMessageResult'; fields: { 'gameChat': { name: 'gameChat'; type: { kind: 'OBJECT'; name: 'GameChat'; ofType: null; } }; 'message': { name: 'message'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'ChatMessage'; ofType: null; }; } }; }; };
    'SendFriendshipInviteInput': { kind: 'INPUT_OBJECT'; name: 'SendFriendshipInviteInput'; isOneOf: false; inputFields: [{ name: 'email'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'SendFriendshipInviteResult': { kind: 'OBJECT'; name: 'SendFriendshipInviteResult'; fields: { 'friendship': { name: 'friendship'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Friendship'; ofType: null; }; } }; 'friendships': { name: 'friendships'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'Friendships'; ofType: null; }; } }; }; };
    'SendGameInviteInput': { kind: 'INPUT_OBJECT'; name: 'SendGameInviteInput'; isOneOf: false; inputFields: [{ name: 'gameSessionId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }]; };
    'String': unknown;
    'SubmitTurnInput': { kind: 'INPUT_OBJECT'; name: 'SubmitTurnInput'; isOneOf: false; inputFields: [{ name: 'gameSessionId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'turn'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'GameTurnInput'; ofType: null; }; }; defaultValue: null }]; };
    'SubmitTurnResult': { kind: 'OBJECT'; name: 'SubmitTurnResult'; fields: { 'gameSession': { name: 'gameSession'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'GameSession'; ofType: null; }; } }; 'gameSessionState': { name: 'gameSessionState'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'GameSessionState'; ofType: null; }; } }; }; };
    'Subscription': { kind: 'OBJECT'; name: 'Subscription'; fields: { 'chatMessageSent': { name: 'chatMessageSent'; type: { kind: 'OBJECT'; name: 'ChatMessage'; ofType: null; } }; 'gameSessionStateChanged': { name: 'gameSessionStateChanged'; type: { kind: 'OBJECT'; name: 'GameSessionState'; ofType: null; } }; }; };
    'Turn': { kind: 'OBJECT'; name: 'Turn'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'data': { name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'JSON'; ofType: null; }; } }; 'roundIndex': { name: 'roundIndex'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'userId': { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; }; };
    'UpdateGameSessionInput': { kind: 'INPUT_OBJECT'; name: 'UpdateGameSessionInput'; isOneOf: false; inputFields: [{ name: 'gameId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }, { name: 'gameSessionId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; }; defaultValue: null }]; };
    'UpdateGameSessionResult': { kind: 'OBJECT'; name: 'UpdateGameSessionResult'; fields: { 'gameSession': { name: 'gameSession'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'GameSession'; ofType: null; }; } }; }; };
    'UpdateUserInfoInput': { kind: 'INPUT_OBJECT'; name: 'UpdateUserInfoInput'; isOneOf: false; inputFields: [{ name: 'color'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'UserColor'; ofType: null; }; }; defaultValue: null }, { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'User': { kind: 'OBJECT'; name: 'User'; fields: { 'color': { name: 'color'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'UserColor'; ofType: null; }; } }; 'email': { name: 'email'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'imageUrl': { name: 'imageUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'isViewer': { name: 'isViewer'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'UserColor': { name: 'UserColor'; enumValues: 'blue' | 'bronze' | 'crimson' | 'gray' | 'indigo' | 'lime' | 'mint' | 'orange' | 'plum' | 'red' | 'teal' | 'violet' | 'yellow'; };
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: 'Subscription';
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}