export const wordBank: string[] = [
  // blanks
  repeat('', 15),

  // common words
  repeat('a', 10),
  repeat('the', 10),
  repeat('and', 10),
  repeat('to', 10),
  repeat('of', 5),
  repeat('in', 5),
  repeat('is', 5),
  repeat('it', 15),
  repeat('that', 5),
  repeat('for', 5),
  repeat('with', 5),
  repeat('on', 5),
  repeat('this', 5),
  repeat('was', 5),
  repeat('as', 5),
  repeat('by', 5),
  repeat('at', 5),
  repeat('an', 5),
  repeat('be', 5),
  repeat('are', 5),
  repeat('from', 5),
  repeat('not', 5),
  repeat('but', 5),
  repeat('or', 5),
  repeat('all', 3),
  repeat('we', 5),
  repeat('you', 5),
  repeat('they', 5),
  repeat('he', 5),
  repeat('she', 5),
  repeat('my', 5),
  repeat('your', 5),
  repeat('his', 5),
  repeat('her', 10),
  repeat('their', 5),
  repeat('our', 5),
  repeat('me', 5),
  repeat('us', 5),
  repeat('him', 5),
  repeat('them', 5),
  repeat('what', 5),
  repeat('who', 5),
  repeat('when', 5),
  repeat('where', 5),
  repeat('why', 5),
  repeat('how', 5),
  repeat('can', 5),
  repeat('will', 5),
  repeat('do', 5),
  repeat('does', 5),
  repeat('did', 5),
  repeat('has', 5),
  repeat('have', 5),
  repeat('had', 5),

  // less common verbs
  repeat('go', 3),
  repeat('get', 3),
  repeat('make', 3),
  repeat('see', 3),
  repeat('know', 3),
  repeat('think', 3),
  repeat('like', 5),
  repeat('want', 3),
  repeat('need', 3),
  repeat('say', 3),
  repeat('tell', 3),
  repeat('show', 3),
  repeat('find', 3),
  repeat('take', 3),
  repeat('give', 3),
  repeat('come', 3),
  repeat('look', 3),
  repeat('try', 3),
  repeat('feel', 3),
  repeat('work', 2),
  repeat('call', 2),
  repeat('put', 2),
  repeat('use', 2),
  repeat('play', 2),
  repeat('run', 2),
  repeat('write', 2),
  repeat('read', 2),
  repeat('talk', 2),
  repeat('listen', 2),
  repeat('watch', 2),
  repeat('help', 2),
  repeat('start', 2),
  repeat('stop', 2),
  repeat('change', 2),
  repeat('turn', 2),
  repeat('move', 2),
  'kill', // getting more interesting / specific
  'impersonate',
  'steal',
  'create',
  'discover',
  'build',
  'position',
  'propose',
  'avoid',
  'kickflip',
  'transform',
  'stab',
  'laugh',
  'cry',
  'sob',
  'scream',
  'whisper',
  'shout',
  'cheer',
  'complain',
  'argue',
  'hoist',
  'jockey',
  'contemplate',
  'ascend',
  'buy',
  // and some past tense too
  repeat('went', 2),
  repeat('got', 2),
  repeat('made', 2),
  repeat('saw', 2),
  repeat('knew', 2),
  repeat('thought', 2),
  repeat('liked', 2),
  repeat('wanted', 2),
  repeat('needed', 2),
  repeat('said', 8),
  repeat('told', 2),
  repeat('showed', 2),
  repeat('found', 2),
  repeat('did', 5),

  // nouns
  repeat('cat', 2),
  repeat('dog', 2),
  repeat('house', 2),
  repeat('car', 2),
  repeat('tree', 2),
  repeat('book', 2),
  repeat('sword', 2),
  repeat('person', 4),
  repeat('water', 2),
  repeat('food', 2),
  repeat('glass', 2),
  repeat('phone', 2),
  repeat('computer', 2),
  repeat('gun', 2),
  repeat('boy', 2),
  repeat('girl', 2),
  repeat('child', 2),
  repeat('mother', 2),
  repeat('father', 2),
  'sibling',
  repeat('friend', 3),
  'stranger',
  'ghost',
  'monster',
  'robot',
  'dragon',
  'idiot',
  'rock',
  'spaceship',
  'planet',
  'space',
  'road',
  'kingdom',
  'castle',
  'city',
  'village',
  'country',
  'world',
  'regent',
  'power',
  'lightning',
  'fire',
  'earthquake',
  'wind',
  'tornado',
  'storm',
  'thunder',
  'light',
  'ice',
  'snow',
  'moon',
  'sun',
  'star',
  'ocean',
  'river',
  'pig',
  'cow',
  'sheep',
  'chicken',
  'fish',
  'bird',
  'elephant',
  'monkey',
  'whale',
  'frog',

  // adjectives
  repeat('big', 2),
  repeat('small', 2),
  repeat('fast', 2),
  repeat('slow', 2),
  repeat('happy', 2),
  repeat('sad', 2),
  repeat('angry', 2),
  repeat('funny', 2),
  repeat('serious', 2),
  repeat('smart', 2),
  repeat('dumb', 2),
  repeat('strong', 2),
  repeat('weak', 2),
  repeat('rich', 2),
  repeat('poor', 2),
  repeat('good', 2),
  repeat('bad', 2),
  repeat('beautiful', 2),
  repeat('ugly', 2),
  repeat('old', 2),
  repeat('young', 2),
  repeat('new', 2),
  'incredible',
  'unhinged',
  'asinine',
  'flat',
  'round',
  'colorful',
  'bright',
  'dark',
  'heavy',
  'rotund',
  'unending',
  'infinite',
  'ancient',
  'ideal',
  'oily',
  'sticky',
  'careful',
  'boisterous',
  'quiet',
  'noisy',

  // adverbs
  repeat('quickly', 2),
  repeat('slowly', 2),
  repeat('happily', 2),
  repeat('sadly', 2),
  repeat('angrily', 2),
  repeat('eagerly', 2),
  repeat('carefully', 2),
  repeat('loudly', 2),
  repeat('quietly', 2),
  repeat('easily', 2),
  repeat('suddenly', 2),
  repeat('silently', 2),
  repeat('gracefully', 2),
  repeat('clumsily', 2),
  repeat('bravely', 2),
  repeat('fiercely', 2),
  repeat('gently', 2),
  repeat('boldly', 2),
  repeat('cautiously', 2),
  repeat('hastily', 2),
  repeat('randomly', 2),
  repeat('deliberately', 2),
  repeat('recklessly', 2),
  repeat('enthusiastically', 2),
  repeat('passionately', 2),
  repeat('mysteriously', 2),
  repeat('absurdly', 2),
  repeat('ridiculously', 2),

  // some punctuation, sparingly
  repeat('!', 5),
  repeat('?', 5),
  repeat('...', 5),

  // for fun
  repeat('$%@#', 3),
].flat();

function repeat(word: string, count: number): string[] {
  return Array.from({ length: count }, () => word);
}
