const groupedWordBank: (string[] | string)[] = [
  // blanks
  repeat('', 15),

  // common words
  repeat('to', 10),
  repeat('of', 5),
  repeat('in', 5),
  repeat('is', 5),
  repeat('it', 15),
  repeat('that', 5),
  repeat('for', 5),
  repeat('with', 5),
  repeat('on', 5),
  repeat('this', 5),
  repeat('was', 5),
  repeat('as', 5),
  repeat('by', 5),
  repeat('at', 5),
  repeat('an', 5),
  repeat('be', 5),
  repeat('are', 5),
  repeat('from', 5),
  repeat('not', 7),
  repeat('but', 5),
  repeat('or', 5),
  repeat('all', 3),
  repeat('we', 5),
  repeat('you', 5),
  repeat('they', 5),
  repeat('he', 5),
  repeat('she', 5),
  repeat('my', 5),
  repeat('your', 5),
  repeat('his', 5),
  repeat('her', 10),
  repeat('their', 5),
  repeat('our', 5),
  repeat('i', 5),
  repeat('me', 5),
  repeat('us', 5),
  repeat('him', 5),
  repeat('them', 5),
  repeat('what', 5),
  repeat('who', 5),
  repeat('when', 5),
  repeat('where', 5),
  repeat('why', 5),
  repeat('how', 5),
  repeat('can', 5),
  repeat('will', 5),
  repeat('do', 5),
  repeat('does', 5),
  repeat('did', 5),
  repeat('has', 5),
  repeat('have', 5),
  repeat('had', 5),
  repeat('because', 3),
  repeat('if', 5),
  repeat('then', 5),
  repeat('there', 5),
  repeat("they're", 5),
  repeat("you're", 5),
  repeat('let', 5),
  repeat('yet', 2),

  // bits
  'ed',
  's',
  'y',
  'ly',
  'ing',
  'er',
  'est',

  // prepositions
  repeat('above', 2),
  repeat('across', 2),
  repeat('after', 2),
  repeat('against', 2),
  repeat('along', 2),
  repeat('among', 2),
  repeat('around', 2),
  repeat('before', 2),
  repeat('behind', 2),
  repeat('below', 2),
  repeat('beneath', 2),
  repeat('beside', 2),
  repeat('between', 2),
  repeat('beyond', 2),
  repeat('during', 2),

  // less common verbs
  repeat('go', 3),
  repeat('get', 3),
  repeat('make', 3),
  repeat('see', 3),
  repeat('know', 3),
  repeat('think', 3),
  repeat('like', 5),
  repeat('want', 3),
  repeat('need', 3),
  repeat('say', 3),
  repeat('tell', 3),
  repeat('show', 3),
  repeat('find', 3),
  repeat('take', 3),
  repeat('give', 3),
  repeat('come', 3),
  repeat('look', 3),
  repeat('try', 3),
  repeat('feel', 3),
  repeat('work', 2),
  repeat('call', 2),
  repeat('put', 2),
  repeat('use', 2),
  repeat('play', 2),
  repeat('run', 2),
  repeat('write', 2),
  repeat('read', 2),
  repeat('talk', 2),
  repeat('listen', 2),
  repeat('watch', 2),
  repeat('help', 2),
  repeat('start', 2),
  repeat('stop', 2),
  repeat('change', 2),
  repeat('turn', 2),
  repeat('move', 2),
  'kill', // getting more interesting / specific
  'impersonate',
  'steal',
  'create',
  'discover',
  'build',
  'position',
  'propose',
  'avoid',
  'kickflip',
  'transform',
  'insult',
  'excite',
  'stab',
  'slay',
  'cook',
  'laugh',
  'cry',
  'sob',
  'scream',
  'whisper',
  'shout',
  'cheer',
  'complain',
  'argue',
  'hoist',
  'jockey',
  'contemplate',
  'ascend',
  'buy',
  'love',
  'hate',
  'beat',
  'seduce',
  'own',
  'wave',
  'lead',
  'poop',
  'remember',
  'crave',
  'despise',
  'balloon',
  'breathe',
  'sneeze',
  'cough',
  'squint',
  'squawk',
  'squirm',
  'squish',
  'mingle',
  'spray',
  'place',
  'judge',
  repeat('train', 2),
  repeat('live', 3),
  // and some past tense too, but just a few
  repeat('went', 2),
  repeat('got', 2),
  repeat('made', 2),
  repeat('saw', 2),
  repeat('said', 8),
  repeat('showed', 2),

  // nouns
  repeat('cat', 2),
  repeat('dog', 2),
  repeat('house', 2),
  repeat('car', 2),
  repeat('tree', 2),
  repeat('book', 2),
  repeat('sword', 2),
  repeat('person', 4),
  repeat('water', 2),
  repeat('food', 2),
  repeat('glass', 2),
  repeat('phone', 2),
  repeat('computer', 2),
  repeat('gun', 2),
  repeat('boy', 2),
  repeat('girl', 2),
  repeat('child', 2),
  repeat('mother', 2),
  repeat('father', 2),
  'sibling',
  repeat('friend', 3),
  repeat('body', 2),
  repeat('hand', 2),
  repeat('foot', 2),
  repeat('head', 2),
  repeat('eye', 1),
  'stranger',
  'ghost',
  'pet',
  'critter',
  'alien',
  'monster',
  'robot',
  'dragon',
  'idiot',
  'rock',
  'spaceship',
  'planet',
  'space',
  'road',
  'kingdom',
  'castle',
  'city',
  'village',
  'country',
  'world',
  'regent',
  'power',
  'lightning',
  'fire',
  'energy',
  'magic',
  'force',
  'earthquake',
  'explosion',
  'wind',
  'tornado',
  'storm',
  'thunder',
  'light',
  'ice',
  'snow',
  'moon',
  'sun',
  'star',
  'ocean',
  'river',
  'pig',
  'cow',
  'sheep',
  'chicken',
  'fish',
  'bird',
  'elephant',
  'monkey',
  'whale',
  'frog',
  'suit',
  'gentleman',
  'lady',
  'hero',
  'ten',
  'hundred',
  'thousand',
  'million',
  'guy',
  "y'all",
  'dude',
  'bro',
  'mark',
  'access',
  'dump',
  'mail',
  'march',
  'aim',
  'matter',
  'skate',
  'mind',
  'excuse',
  'back',
  'mistake',
  'slip',
  'woman',
  'man',
  'queen',
  'king',
  'smell',
  'face',
  'one',
  'two',
  'beam',
  'fight',
  'object',
  'flash',
  'pack',
  'pad',
  'float',
  'paste',
  'bow',
  'break',
  'freeze',
  'podcast',
  'study',
  'bump',
  'glue',
  'cake',
  'grate',
  'plan',
  'surf',
  'surprise',
  'plow',
  'charge',
  'swivel',
  'poke',
  'taste',
  'fly',
  'drag',
  'handle',
  'chip',
  'harm',
  'praise',
  'swing',
  'proceed',
  'clue',
  'color',
  'heap',
  'promise',
  'pump',
  'pull',
  'hold',
  'hug',
  'kiss',
  'rant',
  'cure',
  'iron',
  'cut',
  'itch',
  'repair',
  'damage',
  'repeat',
  'decay',
  'decrease',
  'knock',
  'drain',
  'doubt',
  'dream',
  'load',
  'season',
  'search',
  'wrap',
  'wreck',
  'sense',
  'lock',
  'drill',
  'drink',
  'shape',
  'zone',
  'duck',
  'share',

  // uhh
  repeat('too', 2),
  repeat('very', 2),
  repeat('just', 2),
  repeat('some', 2),
  repeat('also', 2),

  // adjectives
  repeat('big', 2),
  repeat('small', 2),
  repeat('fast', 2),
  repeat('slow', 2),
  repeat('happy', 2),
  repeat('sad', 2),
  repeat('angry', 2),
  repeat('funny', 2),
  repeat('serious', 2),
  repeat('smart', 2),
  repeat('dumb', 2),
  repeat('stupid', 2),
  repeat('lazy', 2),
  repeat('hard', 2),
  repeat('easy', 2),
  repeat('strong', 2),
  repeat('weak', 2),
  repeat('rich', 2),
  repeat('poor', 2),
  repeat('good', 4),
  repeat('bad', 4),
  repeat('beautiful', 2),
  repeat('ugly', 2),
  repeat('old', 2),
  repeat('young', 2),
  repeat('new', 2),
  repeat('high', 2),
  repeat('low', 2),
  repeat('long', 2),
  repeat('short', 2),
  repeat('wide', 2),
  repeat('narrow', 2),
  repeat('deep', 2),
  repeat('shallow', 2),
  'incredible',
  'unhinged',
  'average',
  'asinine',
  'flat',
  'round',
  'colorful',
  'bright',
  'dark',
  'heavy',
  'rotund',
  'unending',
  'infinite',
  'ancient',
  'ideal',
  'oily',
  'sticky',
  'careful',
  'boisterous',
  repeat('quiet', 2),
  'noisy',
  'elaborate',

  // for fun
  repeat('$%@#', 3),
];

// debugging
let seen = new Set<string>();
groupedWordBank.forEach((word) => {
  if (Array.isArray(word)) {
    if (seen.has(word[0])) {
      console.warn(`Duplicate word: ${word[0]}`);
    } else {
      seen.add(word[0]);
    }
  } else {
    if (seen.has(word)) {
      console.warn(`Duplicate word: ${word}`);
    } else {
      seen.add(word);
    }
  }
});

export const wordBank = groupedWordBank.flat() as string[];

export const freebieWords: string[] = [
  '.',
  '!',
  '?',
  '"',
  'a',
  'an',
  'the',
  'and',
];

function repeat(word: string, count: number): string[] {
  return Array.from({ length: count }, () => word);
}
