import { SpeciesType } from './speciesData';

export const names: Record<
  SpeciesType,
  { maleFirst: string[]; femaleFirst: string[]; last: string[] }
> = {
  turtle: {
    maleFirst: [
      'Shelly',
      'Tort',
      'Mortimer',
      'Leon',
      'Franklin',
      'Tank',
      'Moss',
      'Rocky',
      'Herbie',
      'Snap',
    ],
    femaleFirst: [
      'Shelly',
      'Myrtle',
      'Tina',
      'Pebble',
      'Fern',
      'Olive',
      'Sunny',
      'Ruby',
      'Sage',
      'Dot',
    ],
    last: [
      'Greenshell',
      'Slowstride',
      'Riverback',
      'Stonehide',
      'Pondwalker',
      'Shellworth',
      'Mossback',
      'Snapper',
      'Driftwood',
      'Lilypad',
    ],
  },
  fox: {
    maleFirst: [
      'Finn',
      'Rusty',
      'Reed',
      'Ash',
      'Rowan',
      'Cedar',
      'Jasper',
      'Blaze',
      'Sable',
      'Vix',
    ],
    femaleFirst: [
      'Vixie',
      'Amber',
      'Maple',
      'Hazel',
      'Sienna',
      'Ruby',
      'Willow',
      'Scarlet',
      'Autumn',
      'Fern',
    ],
    last: [
      'Swiftpaw',
      'Redtail',
      'Brushwhisk',
      'Quickstep',
      'Shadowfur',
      'Leafrunner',
      'Firefoot',
      'Nightwhisper',
      'Dawnstreak',
      'Bramble',
    ],
  },
  rabbit: {
    maleFirst: [
      'Thistle',
      'Clover',
      'Bram',
      'Pip',
      'Thumper',
      'Bramble',
      'Buck',
      'Hazel',
      'Cotton',
      'Hopper',
    ],
    femaleFirst: [
      'Daisy',
      'Petal',
      'Willow',
      'Clover',
      'Lily',
      'Poppy',
      'Bunny',
      'Fern',
      'Nettle',
      'Blossom',
    ],
    last: [
      'Longfoot',
      'Swiftburrow',
      'Meadowhop',
      'Cottonfur',
      'Thistlewhisk',
      'Cloverpatch',
      'Burrowtail',
      'Hopsworth',
      'Fernfield',
      'Warren',
    ],
  },
  badger: {
    maleFirst: [
      'Brock',
      'Digby',
      'Grubb',
      'Barrow',
      'Mole',
      'Tunneler',
      'Claw',
      'Rooter',
      'Bruno',
      'Digger',
    ],
    femaleFirst: [
      'Mara',
      'Truffle',
      'Honey',
      'Mossy',
      'Hazel',
      'Fern',
      'Brindle',
      'Sable',
      'Tawny',
      'Briar',
    ],
    last: [
      'Earthclaw',
      'Rootsnout',
      'Stonefur',
      'Burrower',
      'Deepdelve',
      'Mossback',
      'Tunnelpaw',
      'Gravelhide',
      'Honeystripe',
      'Barrow',
    ],
  },
  beaver: {
    maleFirst: [
      'Bramble',
      'Timber',
      'Chip',
      'Logan',
      'Brook',
      'Rustle',
      'Cedar',
      'Branch',
      'Moss',
      'Otto',
    ],
    femaleFirst: [
      'Maple',
      'Willow',
      'Hazel',
      'Fern',
      'Aspen',
      'Brook',
      'Pebble',
      'Daisy',
      'Juniper',
      'Pond',
    ],
    last: [
      'Woodwhisk',
      'Damkeeper',
      'Riverbuilder',
      'Logtail',
      'Pondstream',
      'Barkfur',
      'Branchgnaw',
      'Mudpaw',
      'Timberlake',
      'Birchwood',
    ],
  },
  owl: {
    maleFirst: [
      'Hoot',
      'Bartholomew',
      'Strix',
      'Talon',
      'Sage',
      'Wink',
      'Oberon',
      'Birch',
      'Glim',
      'Nimbus',
    ],
    femaleFirst: [
      'Minerva',
      'Wynne',
      'Luna',
      'Hazel',
      'Feather',
      'Glimmer',
      'Aurora',
      'Echo',
      'Sable',
      'Dawn',
    ],
    last: [
      'Nightwing',
      'Feathercrest',
      'Moonwatcher',
      'Silentflight',
      'Starplume',
      'Twilight',
      'Branchperch',
      'Glimfeather',
      'Duskeye',
      'Hollow',
    ],
  },
};
