export const teamAdjectives = [
  'Mighty',
  'Fierce',
  'Swift',
  'Cunning',
  'Brave',
  'Fearless',
  'Noble',
  'Valiant',
  'Sneaky',
  'Gallant',
  'Courageous',
  'Bold',
  'Daring',
  'Intrepid',
  'Vicious',
  'Savage',
  'Ferocious',
  'Relentless',
  'Tenacious',
  'Weird',
  'Wily',
  'Crafty',
  'Sly',
  'Shifty',
  'Cunning',
  'Devious',
  'Tricky',
  'Wicked',
  'Ruthless',
  'Mischievous',
  'Eager',
  'Zealous',
  'Energetic',
  'Incredible',
  'Unstoppable',
  'Legendary',
  'Epic',
  'Mythical',
  'Heroic',
  'Majestic',
  'Radiant',
  'Glorious',
  'Spectacular',
  'Fantastic',
];

export const teamNouns: Array<{ text: string; icon: string }> = [
  { text: 'Suns', icon: '🌞' },
  { text: 'Moons', icon: '🌙' },
  { text: 'Stars', icon: '⭐' },
  { text: 'Blossoms', icon: '🌸' },
  { text: 'Nettles', icon: '🌿' },
  { text: 'Twilight', icon: '🌆' },
  { text: 'Auroras', icon: '🌈' },
  { text: 'Storms', icon: '🌩️' },
  { text: 'Clouds', icon: '☁️' },
  { text: 'Roots', icon: '🪴' },
  { text: 'Pebbles', icon: '🪨' },
  { text: 'Springs', icon: '💧' },
  { text: 'Rain', icon: '🌧️' },
  { text: 'Frost', icon: '❄️' },
  { text: 'Breeze', icon: '💨' },
  { text: 'Willows', icon: '🌳' },
  { text: 'Pines', icon: '🌲' },
  { text: 'Lilies', icon: '🌺' },
  { text: 'Acorns', icon: '🌰' },
  { text: 'Mushrooms', icon: '🍄' },
  { text: 'Dew', icon: '💦' },
  { text: 'Shadows', icon: '🌑' },
  { text: 'Embers', icon: '🔥' },
  { text: 'Valleys', icon: '🏞️' },
  { text: 'Mountains', icon: '⛰️' },
  { text: 'Groves', icon: '🌴' },
  { text: 'Meadows', icon: '🌾' },
  { text: 'Mist', icon: '🌫️' },
  { text: 'Fern', icon: '🪻' },
  { text: 'Boulders', icon: '🪨' },
  { text: 'Knights', icon: '⚔️' },
  { text: 'Tide', icon: '🌊' },
  { text: 'Clover', icon: '🍀' },
  { text: 'Sailors', icon: '⛵' },
  { text: 'Fable', icon: '📖' },
  { text: 'Artists', icon: '🎨' },
  { text: 'Wanderers', icon: '🧭' },
  { text: 'Feathers', icon: '🪶' },
  { text: 'Pawprints', icon: '🐾' },
  { text: 'Merchants', icon: '🪙' },
  { text: 'Builders', icon: '🛠️' },
  { text: 'Mystics', icon: '🔮' },
  { text: 'Protectors', icon: '🛡️' },
  { text: 'Seekers', icon: '🔍' },
  { text: 'Dreamers', icon: '💭' },
  { text: 'Alchemists', icon: '⚗️' },
  { text: 'Royalty', icon: '👑' },
  { text: 'Adventurers', icon: '🏕️' },
  { text: 'Voyagers', icon: '🚀' },
  { text: 'Scribes', icon: '✍️' },
  { text: 'Gems', icon: '💎' },
  { text: 'Spirits', icon: '👻' },
  { text: 'Spiderwebs', icon: '🕸️' },
  { text: 'Wagonwheels', icon: '🛞' },
];
