export const teamAdjectives = [
  'Mighty',
  'Fierce',
  'Swift',
  'Cunning',
  'Brave',
  'Fearless',
  'Noble',
  'Valiant',
  'Sneaky',
  'Gallant',
  'Courageous',
  'Bold',
  'Daring',
  'Intrepid',
  'Vicious',
  'Savage',
  'Ferocious',
  'Relentless',
  'Tenacious',
  'Weird',
  'Wily',
  'Crafty',
  'Sly',
  'Shifty',
  'Cunning',
  'Devious',
  'Tricky',
  'Wicked',
  'Ruthless',
  'Mischievous',
  'Eager',
  'Zealous',
  'Energetic',
];

export const teamNouns: Array<{ text: string; icon: string }> = [
  { text: 'Dragons', icon: '🐉' },
  { text: 'Tigers', icon: '🐅' },
  { text: 'Bears', icon: '🐻' },
  { text: 'Eagles', icon: '🦅' },
  { text: 'Sharks', icon: '🦈' },
  { text: 'Wolves', icon: '🐺' },
  { text: 'Penguins', icon: '🐧' },
  { text: 'Lions', icon: '🦁' },
  { text: 'Bulls', icon: '🐂' },
  { text: 'Panthers', icon: '🐆' },
  { text: 'Rhinos', icon: '🦏' },
  { text: 'Buffaloes', icon: '🐃' },
  { text: 'Cobras', icon: '🐍' },
  { text: 'Scorpions', icon: '🦂' },
  { text: 'Raptors', icon: '🦖' },
  { text: 'Stallions', icon: '🐎' },
  { text: 'Chimera', icon: '🦄' },
  { text: 'Hydra', icon: '🐲' },
  { text: 'Phoenix', icon: '🔥' },
  { text: 'Kraken', icon: '🦑' },
  { text: 'Minotaur', icon: '🐮' },
  { text: 'Cerberus', icon: '🐕' },
  { text: 'Golems', icon: '🪨' },
  { text: 'Basilisks', icon: '🦎' },
  { text: 'Yetis', icon: '🐾' },
  { text: 'Gryphons', icon: '🦅' },
  { text: 'Manticores', icon: '🦁' },
  { text: 'Gargoyles', icon: '🗿' },
  { text: 'Specters', icon: '👻' },
  { text: 'Wraiths', icon: '🌫️' },
  { text: 'Titans', icon: '🗻' },
  { text: 'Djinn', icon: '🧞' },
  { text: 'Ogres', icon: '👹' },
  { text: 'Banshees', icon: '🧟' },
  { text: 'Sprites', icon: '🧚' },
  { text: 'Goblins', icon: '👺' },
];
