// Generated by Wrangler by running `wrangler types --env-interface=DbBindings --config db/wrangler.toml db/src/worker-types.d.ts`

interface DbBindings {
  SESSION_SECRET: string;
  SOCKET_TOKEN_SECRET: string;
  EMAIL_FROM: string;
  UI_ORIGIN: string;
  API_ORIGIN: string;
  GOOGLE_AUTH_CLIENT_ID: string;
  GOOGLE_AUTH_CLIENT_SECRET: string;
  AWS_ACCESS_KEY_ID: string;
  AWS_SECRET_ACCESS_KEY: string;
  D1: D1Database;
  ADMIN_STORE: Service<import('./index.js').AdminStore>;
}
