name = "public-api-service"
compatibility_date = "2025-01-01"
main = "./src/index.ts"

compatibility_flags = ["nodejs_compat"]

[[services]]
binding = "PUBLIC_STORE"
service = "db-service"
entrypoint = "PublicStore"

[[services]]
binding = "ADMIN_STORE"
service = "db-service"
entrypoint = "AdminStore"

[[services]]
binding = "GAME_SESSION_STATE"
service = "game-session-service"
entrypoint = "GameSessionState"
