import {
  red,
  crimson,
  plum,
  violet,
  indigo,
  blue,
  teal,
  green,
  bronze,
  orange,
  yellow,
  mint,
  gray,
} from '@radix-ui/colors';

// this is verbose and manual, because color
// is pretty perceptively varied, so trying
// to abstract these would probably produce
// a bad experience

/** supported player color palettes */
export const colors = {
  red: {
    range: [
      red.red1,
      red.red2,
      red.red3,
      red.red4,
      red.red5,
      red.red6,
      red.red7,
      red.red8,
      red.red9,
      red.red10,
      red.red11,
      red.red12,
    ],
    default: red.red9,
    defaultText: 'white',
  },
  crimson: {
    range: [
      crimson.crimson1,
      crimson.crimson2,
      crimson.crimson3,
      crimson.crimson4,
      crimson.crimson5,
      crimson.crimson6,
      crimson.crimson7,
      crimson.crimson8,
      crimson.crimson9,
      crimson.crimson10,
      crimson.crimson11,
      crimson.crimson12,
    ],
    default: crimson.crimson9,
    defaultText: 'white',
  },
  plum: {
    range: [
      plum.plum1,
      plum.plum2,
      plum.plum3,
      plum.plum4,
      plum.plum5,
      plum.plum6,
      plum.plum7,
      plum.plum8,
      plum.plum9,
      plum.plum10,
      plum.plum11,
      plum.plum12,
    ],
    default: plum.plum9,
    defaultText: 'white',
  },
  violet: {
    range: [
      violet.violet1,
      violet.violet2,
      violet.violet3,
      violet.violet4,
      violet.violet5,
      violet.violet6,
      violet.violet7,
      violet.violet8,
      violet.violet9,
      violet.violet10,
      violet.violet11,
      violet.violet12,
    ],
    default: violet.violet9,
    defaultText: 'white',
  },
  indigo: {
    range: [
      indigo.indigo1,
      indigo.indigo2,
      indigo.indigo3,
      indigo.indigo4,
      indigo.indigo5,
      indigo.indigo6,
      indigo.indigo7,
      indigo.indigo8,
      indigo.indigo9,
      indigo.indigo10,
      indigo.indigo11,
      indigo.indigo12,
    ],
    default: indigo.indigo9,
    defaultText: 'white',
  },
  blue: {
    range: [
      blue.blue1,
      blue.blue2,
      blue.blue3,
      blue.blue4,
      blue.blue5,
      blue.blue6,
      blue.blue7,
      blue.blue8,
      blue.blue9,
      blue.blue10,
      blue.blue11,
      blue.blue12,
    ],
    default: blue.blue9,
    defaultText: 'white',
  },
  teal: {
    range: [
      teal.teal1,
      teal.teal2,
      teal.teal3,
      teal.teal4,
      teal.teal5,
      teal.teal6,
      teal.teal7,
      teal.teal8,
      teal.teal9,
      teal.teal10,
      teal.teal11,
      teal.teal12,
    ],
    default: teal.teal9,
    defaultText: 'white',
  },
  green: {
    range: [
      green.green1,
      green.green2,
      green.green3,
      green.green4,
      green.green5,
      green.green6,
      green.green7,
      green.green8,
      green.green9,
      green.green10,
      green.green11,
      green.green12,
    ],
    default: green.green9,
    defaultText: 'white',
  },
  bronze: {
    range: [
      bronze.bronze1,
      bronze.bronze2,
      bronze.bronze3,
      bronze.bronze4,
      bronze.bronze5,
      bronze.bronze6,
      bronze.bronze7,
      bronze.bronze8,
      bronze.bronze9,
      bronze.bronze10,
      bronze.bronze11,
      bronze.bronze12,
    ],
    default: bronze.bronze9,
    defaultText: 'white',
  },
  orange: {
    range: [
      orange.orange1,
      orange.orange2,
      orange.orange3,
      orange.orange4,
      orange.orange5,
      orange.orange6,
      orange.orange7,
      orange.orange8,
      orange.orange9,
      orange.orange10,
      orange.orange11,
      orange.orange12,
    ],
    default: orange.orange9,
    defaultText: 'white',
  },
  yellow: {
    range: [
      yellow.yellow1,
      yellow.yellow2,
      yellow.yellow3,
      yellow.yellow4,
      yellow.yellow5,
      yellow.yellow6,
      yellow.yellow7,
      yellow.yellow8,
      yellow.yellow9,
      yellow.yellow10,
      yellow.yellow11,
      yellow.yellow12,
    ],
    default: yellow.yellow9,
    defaultText: 'black',
  },
  mint: {
    range: [
      mint.mint1,
      mint.mint2,
      mint.mint3,
      mint.mint4,
      mint.mint5,
      mint.mint6,
      mint.mint7,
      mint.mint8,
      mint.mint9,
      mint.mint10,
      mint.mint11,
      mint.mint12,
    ],
    default: mint.mint9,
    defaultText: 'black',
  },
  gray: {
    range: [
      gray.gray1,
      gray.gray2,
      gray.gray3,
      gray.gray4,
      gray.gray5,
      gray.gray6,
      gray.gray7,
      gray.gray8,
      gray.gray9,
      gray.gray10,
      gray.gray11,
      gray.gray12,
    ],
    default: gray.gray9,
    defaultText: 'black',
  },
};

export type PlayerColorName = keyof typeof colors;
