name = "prod-long-game-db-service"
compatibility_date = "2025-01-01"
main = "./src/index.ts"
account_id = "5f843fcad78a2f4e1fee091c1d6c21ab"

compatibility_flags = ["nodejs_compat"]

[vars]
# ! removes game session limits
DEV_MODE = false

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[[d1_databases]]
binding = "D1"
database_name = "prod-long-game-core"
database_id = "19289791-c695-4c46-8ad9-116b947fce1d"

[[services]]
binding = "ADMIN_STORE"
service = "prod-long-game-db-service"
entrypoint = "AdminStore"
