name: "Game: Deploy Hearts v1"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install deps
        run: pnpm i --filter "@long-game/game-hearts-v1..."

      - name: Build game
        run: pnpm --filter "@long-game/game-hearts-v1..." run build
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Run tests
        run: pnpm --filter "@long-game/game-hearts-v1..." run test --run

      - name: Deploy Game Service
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          workingDirectory: ./games/hearts/v1
          command: deploy -c ./wrangler.jsonc
