name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Write .env to app dir
        run: |
          echo "PUBLIC_API_ORIGIN=${{ vars.PUBLIC_API_ORIGIN }}" >> ./app/.env
          echo "PUBLIC_APP_ORIGIN=${{ vars.APP_ORIGIN }}" >> ./app/.env
          echo "PUBLIC_VAPID_PUBLIC_KEY=${{ secrets.VAPID_PUBLIC_KEY }}" >> ./app/.env
      - name: Build everything
        run: pnpm run build
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Run Playwright tests
        run: pnpm exec playwright test
        env:
          API_ORIGIN: https://api.rout.games
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
