// Generated by Wrangler by running `wrangler types --env-interface=ApiBindings --config api/wrangler.toml api/src/worker-types.d.ts`

interface ApiBindings {
  NODE_ENV: 'production';
  SESSION_SECRET: string;
  SOCKET_TOKEN_SECRET: string;
  EMAIL_FROM: string;
  UI_ORIGIN: string;
  API_ORIGIN: string;
  DEV_MODE: boolean;
  GOOGLE_AUTH_CLIENT_ID: string;
  GOOGLE_AUTH_CLIENT_SECRET: string;
  AWS_ACCESS_KEY_ID: string;
  AWS_SECRET_ACCESS_KEY: string;
  VAPID_PUBLIC_KEY: string;
  VAPID_PRIVATE_KEY: string;
  GAME_SESSION_STATE: DurableObjectNamespace<
    import('./index').GameSessionState
  >;
  PUBLIC_STORE: Service<import('@long-game/service-db').PublicStore>;
  ADMIN_STORE: Service<import('@long-game/service-db').AdminStore>;
}
